[package]
name = "testingGit"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full", "rt-multi-thread"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

